# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edbb6bfed343ea7d78459d0c23d4cfe255c12737773fa4a7c10d55a6e9f9296d1d39b2d9c9637ac8e3a883a18170699ca37bc85fd317a8eb7c91de674f076fcb

test:
  secret_key_base: 4682e323e4232cd75f5e534d4458bd902f8c9f448a018a2971cb25da829acb01fa5d348ff28e9db9aedd8f2dcf2e862b267dca8695e5f75c2103d59c5b61ea7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
